apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}-route
spec:
  parentRefs:
    - name: kong
  hostnames:
    - "polbro.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Chart.Name }}
          kind: Service
          port: {{ .Values.service.port }}
