apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}-route
spec:
  parentRefs:
    - name: kong
  hostnames:
    - "polbro.local" 
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/polling
      backendRefs:
        - name: {{ .Chart.Name }}
          kind: Service
          port: {{ .Values.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: {{ .Chart.Name }}
          kind: Service
          port: {{ .Values.service.port }}