apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "polling-chart.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  # Loop through secrets and Base64 encode each value
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}