apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-monitor
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      # This matches the labels in your _helpers.tpl
      name: {{ .Values.app.name }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics